#ifndef CODE_CONFIG_H
#define CODE_CONFIG_H

#define DEPLOY_UTESTS 1

#define DEPLOY_TCP_SERVER 1
#define DEPLOY_TCP_CLIENT 0
#define DEPLOY_SCAN_COM 0
#define HIDE_CONSOLE 0


#define DEPLOY_PARSE_REG 0
#define PRINT_ENV 0

#define TCP_BOARD_SERVER_PORT 50506

#endif /* CODE_CONFIG_H */
