#ifndef CODE_CONFIG_H
#define CODE_CONFIG_H

#define DEPLOY_UTESTS 1

#define HIDE_CONSOLE 0
#define PRINT_ENV 0

#define DFLT_TCP_BOARD_SERVER_PORT 50506

#if DEPLOY_TCP_CLIENT
#define DFLT_TCP_BOARD_SERVER_IP "192.168.0.11"
#endif

#endif /* CODE_CONFIG_H */
