#ifndef CODE_CONFIG_H
#define CODE_CONFIG_H

#define DEPLOY_UTESTS 1

#define DEPLOY_TCP_SERVER 0
#define DEPLOY_TCP_CLIENT 0
#define DEPLOY_SCAN_COM 0
#define HIDE_CONSOLE 0

#define DEPLOY_PARSE_REG 1
#define PRINT_ENV 0

#define DFLT_TCP_BOARD_SERVER_PORT 50506

#if DEPLOY_TCP_CLIENT
#define DFLT_TCP_BOARD_SERVER_IP "192.168.0.11"
#endif

#endif /* CODE_CONFIG_H */
