#PROJECT_ROOT = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

#@echo $(error PROJECT_ROOT= $(PROJECT_ROOT))
#SRC_PATH :=  $(dir $(abspath $(dir $$PWD) ))

#@echo $(error SRC_PATH=$(SRC_PATH))

#CC=clang           

all: main.c
	clang  main.c -o hello
